const universityMap = new Map([
  ["University of North Carolina at Chapel Hill", 1],
  ["North Carolina State University at Raleigh", 2],
  ["University of California Los Angeles", 3],
  ["University of Virginia Main Campus", 4],
  ["University of Miami", 5],
  ["Clemson University", 6],
  ["Stanford University", 7],
  ["University of South Carolina Columbia", 8],
  ["Scripps College", 9],
  ["College of William and Mary", 10],
  ["University of Maryland College Park", 11],
  ["University of Florida", 12],
  ["University of North Carolina at Wilmington", 13],
  ["Appalachian State University", 14],
  ["Harvard University", 15],
  ["Elizabeth City State University", 16],
  ["University of Chicago", 17],
  ["Elon University", 18],
  ["University of California Davis", 19],
  ["University of North Carolina at Asheville", 20],
  ["University of Pittsburgh Pittsburgh Campus", 21],
  ["Rose Hulman Institute of Technology", 22],
  ["University of California Santa Barbara", 23],
  ["Georgia Institute of Technology Main Campus", 24],
  ["Virginia Polytechnic Institute and State University", 25],
  ["Hendrix College", 26],
  ["Illinois Institute of Technology", 27],
  ["New College of Florida", 28],
  ["Smith College", 29],
  ["University of California Irvine", 30],
  ["Davidson College", 31],
  ["Franklin W. Olin College of Engineering", 32],
  ["Kenyon College", 33],
  ["Lewis & Clark College", 34],
  ["Reed College", 35],
  ["The University of Texas at Dallas", 36],
  ["University of Pennsylvania", 37],
  ["Worcester Polytechnic Institute", 38],
  ["Converse College", 39],
  ["Florida State University", 40],
  ["United States Air Force Academy", 41],
  ["University of San Diego", 42],
  ["Brandeis University", 43],
  ["California Polytechnic State University San Luis Obispo", 44],
  ["Princeton University", 45],
  ["Soka University of America", 46],
  ["Stetson University", 47],
  ["University of California Berkeley", 48],
  ["University of Georgia", 49],
  ["University of South Florida Main Campus", 50],
  ["Villanova University", 51],
  ["Pitzer College", 52],
  ["The University of Tennessee", 53],
  ["Barnard College", 54],
  ["College of Charleston", 55],
  ["Florida International University", 56],
  ["University of Wisconsin Madison", 57],
  ["University of Dallas", 58],
  ["University of Michigan Ann Arbor", 59],
  ["University of North Carolina at Charlotte", 60],
  ["Rensselaer Polytechnic Institute - New York", 81],
  ["University of Central Florida - Florida", 82],
  ["Winthrop University - South Carolina", 83],
  ["Brigham Young University Provo - Utah", 84],
  ["Colorado School of Mines - Colorado", 85],
  ["Emory University - Georgia", 86],
  ["Stony Brook University - New York", 87],
  ["SUNY College of Environmental Science and Forestry - New York", 88],
  ["University of Rochester - New York", 89],
  ["University of Tulsa - Oklahoma", 90],
  ["Vassar College - New York", 91],
  ["Westmont College - California", 92],
  ["Nova Southeastern University", 73],
  ["United States Coast Guard Academy", 74],
  ["Point Loma Nazarene University", 75],
  ["Rhodes College", 76],
  ["Thomas Aquinas College", 77],
  ["University of La Verne", 78],
  ["Butler University", 79],
  ["Saint Louis University Main Campus", 80],
  ["Whitman College", 93],
  ["Whitworth University", 94],
  ["Berry College", 95],
  ["Christian Brothers University", 96],
  ["Gonzaga University", 97],
  ["Hope College", 98],
  ["Messiah College", 99],
  ["University of Massachusetts Amherst", 100],
  ["University of North Florida", 101],
  ["University of Southern California", 102],
  ["Wesleyan University", 103],
  ["Gardner Webb University", 104],
  ["John Brown University", 105],
  ["Loyola Marymount University", 106],
  ["Columbia College", 107],
  ["Mercer University", 108],
  ["Salisbury University", 109],
  ["Taylor University", 110],
  ["Wheaton College - Illinois", 111],
  ["Albany College of Pharmacy and Health Sciences", 112],
  ["Christopher Newport University", 113],
  ["Drake University", 114],
  ["Drury University", 115],
  ["Duquesne University", 116],
  ["Lawrence University", 117],
  ["Lenoir Rhyne University", 118],
  ["Maryville University of Saint Louis", 119],
  ["Ohio Northern University", 120],
  ["Purdue University Main Campus", 121],
  ["Southern Methodist University", 122],
  ["Texas Lutheran University", 123],
  ["Transylvania University", 124],
  ["University of South Carolina Upstate", 125],
  ["Agnes Scott College", 126],
  ["Augustana College - South Dakota", 127],
  ["Bradley University", 128],
  ["Carnegie Mellon University", 129],
  ["Franciscan University of Steubenville", 130],
  ["Milwaukee School of Engineering", 131],
  ["Saint Mary's College", 132],
  ["Willamette University", 133],
  ["Chapman University", 134],
  ["New Mexico Institute of Mining and Technology", 135],
  ["Notre Dame of Maryland University", 136],
  ["Samford University", 137],
  ["William Jewell College", 138],
  ["Calvin College", 139],
  ["College of Saint Benedict", 140],
  ["Hanover College", 141],
  ["Rockhurst University", 142],
  ["Union University", 143],
  ["University of Denver", 144],
  ["University of North Carolina School of the Arts", 145],
  ["Wabash College", 146],
  ["Western Carolina University", 147],
  ["Asbury University", 148],
  ["Columbia International University", 149],
  ["George Mason University", 150],
  ["Gustavus Adolphus College", 151],
  ["Lander University", 152],
  ["Linfield College McMinnville Campus", 153],
  ["Luther College", 154],
  ["Pacific Lutheran University", 155],
  ["Santa Clara University", 156],
  ["The College of Wooster", 157],
  ["Arcadia University", 158],
  ["California Lutheran University", 159],
  ["DePaul University", 160],
  ["Loyola University Chicago", 161],
  ["Azusa Pacific University", 162],
  ["Cedarville University", 163],
  ["Colgate University", 164],
  ["Mills College", 165],
  ["Oklahoma Baptist University", 166],
  ["University of Alabama at Huntsville", 167],
  ["University of Dayton", 168],
  ["University of North Carolina at Greensboro", 169],
  ["Hardin Simmons University", 170],
  ["Lake Forest College", 171],
  ["Miami University Oxford", 172],
  ["Pratt Institute Main", 173],
  ["The Master's College and Seminary", 174],
  ["University of Portland", 175],
  ["Concordia College at Moorhead", 176],
  ["Daemen College", 177],
  ["Florida Southern College", 178],
  ["Indiana University Bloomington", 179],
  ["LeTourneau University", 180],
  ["Michigan State University", 181],
  ["St Olaf College", 182],
  ["University of Alabama at Birmingham", 183],
  ["University of Arkansas", 184],
  ["University of Minnesota Morris", 185],
  ["Xavier University", 186],
  ["Central College", 187],
  ["Colorado State University Fort Collins", 188],
  ["Francis Marion University", 189],
  ["Kettering University", 190],
  ["Randolph College", 191],
  ["Saint Marys College of California", 192],
  ["St Catherine University", 193],
  ["Towson University", 194],
  ["University of Iowa", 195],
  ["University of San Francisco", 196],
  ["University of St Thomas - Texas", 197],
  ["University of the Sciences", 198],
  ["University of Wisconsin River Falls", 199],
  ["Virginia Military Institute", 200],
  ["Babson College", 201],
  ["Belmont University", 202],
  ["Canisius College", 203],
  ["Chatham University", 204],
  ["College of Saint Mary", 205],
  ["Concordia University Seward", 206],
  ["Cooper Union for the Advancement of Science and Art", 207],
  ["Covenant College", 208],
  ["CUNY Queens College", 209],
  ["Denison University", 210],
  ["Drexel University", 211],
  ["Emerson College", 212],
  ["Emmanuel College - Massachusetts", 213],
  ["Iowa State University", 214],
  ["Lyon College", 215],
  ["Michigan Technological University", 216],
  ["Milligan College", 217],
  ["Missouri University of Science and Technology", 218],
  ["New York University", 219],
  ["Occidental College", 220],
  ["Pacific University", 221],
  ["Rochester Institute of Technology", 222],
  ["San Diego State University", 223],
  ["Sarah Lawrence College", 224],
  ["Sewanee The University of the South", 225],
  ["SUNY at Binghamton", 226],
  ["SUNY at Geneseo", 227],
  ["SUNY College at Oneonta", 228],
  ["Syracuse University", 229],
  ["The College of Idaho", 230],
  ["The University of Alabama", 231],
  ["University of California Riverside", 232],
  ["University of Oregon", 233],
  ["University of Redlands", 234],
  ["Valparaiso University", 235],
  ["Wagner College", 236],
  ["Boston University", 237],
  ["Dominican University", 238],
  ["East Carolina University", 239],
  ["Fordham University", 240],
  ["Indiana Wesleyan University", 241],
  ["North Central College", 242],
  ["Oklahoma City University", 243],
  ["Pennsylvania State University Main Campus", 244],
  ["Pepperdine University", 245],
  ["University of Oklahoma Norman Campus", 246],
  ["Abilene Christian University", 247],
  ["Clark University", 248],
  ["Coe College", 249],
  ["Embry Riddle Aeronautical University Prescott", 250],
  ["Florida Institute of Technology", 251],
  ["Harding University", 252],
  ["Missouri State University Springfield", 253],
  ["Seattle University", 254],
  ["University of South Carolina Aiken", 255],
  ["Virginia Commonwealth University", 256],
  ["Corban University", 257],
  ["Oberlin College", 258],
  ["Queens University of Charlotte", 259],
  ["Randolph Macon College", 260],
  ["Saint Francis University", 261],
  ["Waynesburg University", 262],
  ["Austin College", 263],
  ["Clarkson University", 264],
  ["College of the Atlantic", 265],
  ["Embry Riddle Aeronautical University Daytona Beach", 266],
  ["George Fox University", 267],
  ["Gordon College - Massachusetts", 268],
  ["Illinois College", 269],
  ["Lipscomb University", 270],
  ["Northwest Nazarene University", 271],
  ["Oregon State University", 272],
  ["University of Colorado Boulder", 273],
  ["University of Mary Hardin Baylor", 274],
  ["Millsaps College", 275],
  ["Newman University", 276],
  ["Seattle Pacific University", 277],
  ["Spelman College", 278],
  ["University of St Thomas - Minnesota", 279],
  ["University of Utah", 280],
  ["Biola University", 281],
  ["Bucknell University", 282],
  ["Carroll College", 283],
  ["Loyola University New Orleans", 284],
  ["Regis University", 285],
  ["Seton Hill University", 286],
  ["University of Michigan Dearborn", 287],
  ["Wofford College", 288],
  ["York College Pennsylvania", 289],
  ["Centenary College of Louisiana", 290],
  ["Citadel Military College of South Carolina", 291],
  ["Cornell College", 292],
  ["Flagler College St Augustine", 293],
  ["Freed Hardeman University", 294],
  ["Houghton College", 295],
  ["John Carroll University", 296],
  ["Lee University", 297],
  ["Northwestern College - Iowa", 298],
  ["Oklahoma State University Main Campus", 299],
  ["Ouachita Baptist University", 300],
  ["Saint Vincent College", 301],
  ["University of Louisville", 302],
  ["Walla Walla University", 303],
  ["Washington College", 304],
  ["Clarke University", 305],
  ["Gannon University", 306],
  ["Grand Valley State University", 307],
  ["Hood College", 308],
  ["McMurry University", 309],
  ["Schreiner University", 310],
  ["West Chester University of Pennsylvania", 311],
  ["Bellarmine University", 312],
  ["Bethel University - Minnesota", 313],
  ["Delaware Valley College", 314],
  ["Hofstra University", 315],
  ["Northwestern College - Minnesota", 316],
  ["Saint Johns University", 317],
  ["Saint Joseph's University", 318],
  ["Simpson University", 319],
  ["Sweet Briar College", 320],
  ["University of California Merced - California", 341],
  ["University of Mary Washington - Virginia", 342],
  ["Yeshiva University - New York", 343],
  ["Adelphi University - New York", 344],
  ["Albion College - Michigan", 345],
  ["Alma College - Michigan", 346],
  ["Anderson University - South Carolina", 347],
  ["Aquinas College - Tennessee", 348],
  ["Ave Maria University - Florida", 349],
  ["Baldwin Wallace College - Ohio", 350],
  ["Bard College - New York", 351],
  ["Bennington College - Vermont", 352],
  ["Bridgewater College - Virginia", 353],
  ["California State University Long Beach - California", 354],
  ["Colorado Christian University - Colorado", 355],
  ["Dallas Baptist University - Texas", 356],
  ["Doane College Crete - Nebraska", 357],
  ["Dominican University of California", 338],
  ["Dordt College", 339],
  ["Earlham College", 340],
  ["South Dakota School of Mines and Technology", 358],
  ["Southern Utah University", 359],
  ["SUNY at Albany", 360],
  ["SUNY College at Oswego", 361],
  ["Tennessee Technological University", 362],
  ["Touro College", 363],
  ["Trine University", 364],
  ["Trinity University", 365],
  ["Tulane University of Louisiana", 366],
  ["Union College - New York", 367],
  ["University of Delaware", 368],
  ["University of Kansas", 369],
  ["University of Mississippi", 370],
  ["Warren Wilson College", 371],
  ["Wells College", 372],
  ["Westminster College - Utah", 373],
  ["Wheaton College - Massachusetts", 374],
  ["William Woods University", 375],
  ["Andrews University", 376],
  ["Bethel College Mishawaka", 377],
  ["Cornerstone University", 378],
  ["Martin Luther College", 379],
  ["Mississippi College", 380],
  ["Montana Tech of the University of Montana", 381],
  ["St Lawrence University", 382],
  ["The College of Saint Scholastica", 383],
  ["Birmingham Southern College", 384],
  ["California State University Fullerton", 385],
  ["Hamline University", 386],
  ["University of the Incarnate Word", 387],
  ["University of Wyoming", 388],
  ["VanderCook College of Music", 389],
  ["Viterbo University", 390],
  ["Baker University", 391],
  ["Caldwell College", 392],
  ["Grace College and Theological Seminary", 393],
  ["Kansas State University", 394],
  ["Presbyterian College", 395],
  ["University of the Pacific", 396],
  ["Wartburg College", 397],
  ["Whittier College", 398],
  ["Wichita State University", 399],
  ["Aquinas College - Michigan", 400],
  ["Florida Atlantic University - Florida", 421],
  ["Huntington University - Indiana", 422],
  ["Lafayette College", 403],
  ["Northwest University", 404],
  ["Robert Morris University", 405],
  ["Saint Michael's College", 406],
  ["Saint Norbert College", 407],
  ["Savannah College of Art and Design", 408],
  ["Southwest Baptist University", 409],
  ["University of Cincinnati Main Campus", 410],
  ["University of Hawaii at Manoa", 411],
  ["University of Kentucky", 412],
  ["University of Missouri St Louis", 413],
  ["University of Pittsburgh Greensburg", 414],
  ["Utah State University", 415],
  ["Webster University", 416],
  ["West Virginia Wesleyan College", 417],
  ["Westminster College - Pennsylvania", 418],
  ["Hampshire College", 419],
  ["Laguna College of Art and Design", 420],
  ["Maryland Institute College of Art", 423],
  ["Maryville College", 424],
  ["Oral Roberts University", 425],
  ["Saint Martin's University", 426],
  ["Spring Hill College", 427],
  ["University of Indianapolis", 428],
  ["University of Wisconsin Stevens Point", 429],
  ["Arkansas State University Main Campus", 430],
  ["Capital University", 431],
  ["Eastern University", 432],
  ["Hastings College", 433],
  ["Lincoln Memorial University", 434],
  ["Lycoming College", 435],
  ["Roanoke College", 436],
  ["Southwestern College", 437],
  ["The University of Tennessee Martin", 438],
  ["University of Illinois at Springfield", 439],
  ["Westminster College - Missouri", 440],
  ["Louisiana State University and Agricultural & Mechanical College", 441],
  ["Beloit College", 442],
  ["California State Polytechnic University Pomona", 443],
  ["Louisiana Tech University", 444],
  ["Midwestern State University", 445],
  ["Mount Marty College", 446],
  ["Multnomah University", 447],
  ["Philadelphia University", 448],
  ["The University of West Florida", 449],
  ["University of Colorado Denver", 450],
  ["University of Minnesota Duluth", 451],
  ["University of Science and Arts of Oklahoma", 452],
  ["University of St Francis", 453],
  ["Arizona State University", 454],
  ["Ball State University", 455],
  ["Baptist Memorial College of Health Sciences", 456],
  ["Central Methodist University College of Liberal Arts & Sciences", 457],
  ["Concordia University Irvine", 458],
  ["Concordia University Portland", 459],
  ["Le Moyne College", 460],
  ["Loras College", 461],
  ["Mount St Mary's University", 462],
  ["Ohio University Main Campus", 463],
  ["University of Arizona", 464],
  ["Western Washington University", 465],
  ["Marietta College", 466],
  ["Nebraska Methodist College of Nursing & Allied Health", 467],
  ["North Dakota State University Main Campus", 468],
  ["Temple University", 469],
  ["Anderson University - Indiana", 470],
  ["Boise State University", 471],
  ["Brigham Young University Idaho", 472],
  ["Buena Vista University", 473],
  ["Carson Newman College", 474],
  ["Coastal Carolina University", 475],
  ["Franklin College", 476],
  ["Georgia College & State University", 477],
  ["Gettysburg College", 478],
  ["Hampden Sydney College", 479],
  ["King College", 480],
  ["Lawrence Technological University", 481],
  ["Marian University - Indiana", 482],
  ["Marshall University", 483],
  ["McKendree University", 484],
  ["Monmouth University", 485],
  ["Mount Mercy University", 486],
  ["Niagara University", 487],
  ["North Greenville University", 488],
  ["Northern Arizona University", 489],
  ["Ohio Wesleyan University", 490],
  ["Piedmont College", 491],
  ["Quinnipiac University", 492],
  ["School of the Art Institute of Chicago", 493],
  ["Simmons College", 494],
  ["Slippery Rock University of Pennsylvania", 495],
  ["Southwestern Oklahoma State University", 496],
  ["St John's University New York", 497],
  ["St. Mary's University", 498],
  ["The University of Texas at Tyler", 499],
  ["University of Nebraska at Omaha", 500],
  ["University of Pittsburgh Johnstown - Pennsylvania", 521],
  ["University of South Alabama", 502],
  ["Washburn University", 503],
  ["Widener University Main Campus", 504],
  ["Wisconsin Lutheran College", 505],
  ["Wittenberg University", 506],
  ["Faith Baptist Bible College and Theological Seminary", 507],
  ["Hawaii Pacific University", 508],
  ["Jacksonville University", 509],
  ["Lewis University", 510],
  ["Murray State University", 511],
  ["New York School of Interior Design", 512],
  ["Northwest Christian University", 513],
  ["Quincy University", 514],
  ["Roberts Wesleyan College", 515],
  ["Shenandoah University", 516],
  ["Southern Virginia University", 517],
  ["Spring Arbor University", 518],
  ["University of Idaho", 519],
  ["University of Nebraska at Kearney", 520],
  ["Greenville College", 522],
  ["Jefferson College of Health Sciences", 523],
  ["Moravian College and Moravian Theological Seminary", 524],
  ["Morningside College", 525],
  ["Portland State University", 526],
  ["Trinity Christian College", 527],
  ["University of Charleston", 528],
  ["Wheeling Jesuit University", 529],
  ["Bethel College North Newton", 530],
  ["Florida Gulf Coast University", 531],
  ["Huntingdon College", 532],
  ["Longwood University", 533],
  ["Lubbock Christian University", 534],
  ["Massachusetts College of Art and Design", 535],
  ["Mercyhurst College", 536],
  ["Oakland University", 537],
  ["Providence College", 538],
  ["The University of Tennessee at Chattanooga", 539],
  ["Toccoa Falls College", 540],
  ["University of Nevada Reno", 541],
  ["University of Scranton", 542],
  ["University of Wisconsin Green Bay", 543],
  ["Xavier University of Louisiana", 544],
  ["Bluefield State College", 545],
  ["Crown College", 546],
  ["Fairfield University", 547],
  ["Illinois State University", 548],
  ["Manchester College", 549],
  ["Marywood University", 550],
  ["McNeese State University", 551],
  ["Millikin University", 552],
  ["Northwest Missouri State University", 553],
  ["University of South Dakota", 554],
  ["West Virginia University", 555],
  ["Middle Tennessee State University", 556],
  ["Morehead State University", 557],
  ["Northwood University Texas", 558],
  ["Pacific Union College", 559],
  ["University of Louisiana Monroe", 560],
  ["University of Massachusetts Dartmouth", 561],
  ["University of Montevallo", 562],
  ["Walsh University", 563],
  ["William Jessup University", 564],
  ["Concordia University Wisconsin", 565],
  ["Eckerd College", 566],
  ["Georgia State University", 567],
  ["King's College", 568],
  ["LaGrange College", 569],
  ["Mount St. Mary's College", 570],
  ["Mount Vernon Nazarene University", 571],
  ["Ohio Dominican University", 572],
  ["Stonehill College", 573],
  ["The University of Virginia's College at Wise", 574],
  ["University of Hawaii at Hilo", 575],
  ["University of Mobile", 576],
  ["Ursuline College", 577],
  ["Wingate University", 578],
  ["Albright College", 579],
  ["Bethany Lutheran College", 580],
  ["California Baptist University", 581],
  ["California State University Fresno", 582],
  ["Catholic University of America", 583],
  ["East Texas Baptist University", 584],
  ["Eastern Illinois University", 585],
  ["Georgetown College", 586],
  ["Indiana University Purdue University Indianapolis", 587],
  ["La Sierra University", 588],
  ["Susquehanna University", 589],
  ["University of Memphis", 590],
  ["Washington & Jefferson College", 591],
  ["West Liberty University", 592],
  ["Assumption College", 593],
  ["Belhaven University", 594],
  ["Blackburn College", 595],
  ["Central Michigan University", 596],
  ["Clearwater Christian College", 597],
  ["Drew University", 598],
  ["Elmhurst College", 599],
  ["Hobart William Smith Colleges", 600],
  ["Mississippi State University", 601],
  ["Newberry College", 602],
  ["Our Lady of the Lake College", 603],
  ["South Dakota State University", 604],
  ["Western New England University", 605],
  ["Baptist Bible College and Seminary", 606],
  ["Carthage College", 607],
  ["Emporia State University", 608],
  ["Judson College", 609],
  ["Judson University", 610],
  ["Kent State University at Kent", 611],
  ["Mansfield University of Pennsylvania", 612],
  ["Minot State University", 613],
  ["Northeastern State University", 614],
  ["San Jose State University", 615],
  ["Texas Wesleyan University", 616],
  ["University of Colorado Colorado Springs", 617],
  ["University of Missouri Kansas City", 618],
  ["University of New Haven", 619],
  ["Ashland University", 620],
  ["Bloomsburg University of Pennsylvania", 621],
  ["Bowling Green State University Main Campus", 622],
  ["Bryant University", 623],
  ["Carroll University", 624],
  ["College of Mount Saint Vincent", 625],
  ["Concordia University Texas", 626],
  ["Cumberland University", 627],
  ["East Central University", 628],
  ["East Tennessee State University", 629],
  ["Edgewood College", 630],
  ["Farmingdale State College", 631],
  ["Fresno Pacific University", 632],
  ["Hampton University", 633],
  ["Madonna University", 634],
  ["Malone University", 635],
  ["Marist College", 636],
  ["Mary Baldwin College", 637],
  ["Misericordia University", 638],
  ["Montana State University", 639],
  ["Mount Aloysius College", 640],
  ["Northland College", 641],
  ["Pace University New York", 642],
  ["Pittsburg State University", 643],
  ["Rider University", 644],
  ["Sacred Heart University", 645],
  ["Saint Bonaventure University", 646],
  ["Saint Joseph College", 647],
  ["Southeast Missouri State University", 648],
  ["Southern Oregon University", 649],
  ["Stephens College", 650],
  ["Sterling College - Kansas", 651],
  ["SUNY at Fredonia", 652],
  ["Texas A & M University Kingsville", 653],
  ["The University of Findlay", 654],
  ["The University of Tampa", 655],
  ["Thomas More College", 656],
  ["Trevecca Nazarene University", 657],
  ["Union College - Nebraska", 658],
  ["University of Central Arkansas", 659],
  ["University of Central Oklahoma", 660],
  ["University of New Mexico Main Campus", 661],
  ["University of Rhode Island", 662],
  ["University of South Carolina Beaufort", 663],
  ["University of the Cumberlands", 664],
  ["University of Wisconsin Oshkosh", 665],
  ["Virginia Wesleyan College", 666],
  ["Washington State University", 667],
  ["Winona State University", 668],
  ["Chaminade University of Honolulu", 669],
  ["Friends University", 670],
  ["La Salle University", 671],
  ["Lincoln Christian University", 672],
  ["Lynchburg College", 673],
  ["Muhlenberg College", 674],
  ["Rocky Mountain College", 675],
  ["Saint Gregorys University", 676],
  ["University of Illinois at Chicago", 677],
  ["University of Massachusetts Lowell", 678],
  ["University of North Carolina at Pembroke", 679],
  ["University of Northern Colorado", 680],
  ["University of Saint Mary - Kansas", 681],
  ["Claflin University", 682],
  ["Eureka College", 683],
  ["Graceland University Lamoni", 684],
  ["Lock Haven University", 685],
  ["Midway College", 686],
  ["Saint Ambrose University", 687],
  ["Southern Polytechnic State University", 688],
  ["Western Michigan University", 689],
  ["Young Harris College", 690],
  ["Alvernia University", 691],
  ["American Jewish University", 692],
  ["Florida Agricultural and Mechanical University", 693],
  ["Johnson University", 694],
  ["Kentucky Wesleyan College", 695],
  ["Point University", 696],
  ["Ramapo College of New Jersey", 697],
  ["Shepherd University", 698],
  ["Southeastern Oklahoma State University", 699],
  ["University of Central Missouri", 700],
  ["University of Saint Mary - Michigan", 701],
  ["California State University Stanislaus", 702],
  ["Cedar Crest College", 703],
  ["Fairmont State University", 704],
  ["Old Dominion University", 705],
  ["Rollins College", 706],
  ["University of New England", 707],
  ["Art Center College of Design", 708],
  ["Avila University", 709],
  ["California State University Sacramento", 710],
  ["Endicott College", 711],
  ["Fort Hays State University", 712],
  ["Northwood University Michigan", 713],
  ["Pennsylvania State University Penn State Erie Behrend College", 714],
  ["Saint Joseph's College New York", 715],
  ["Shorter University", 716],
  ["Tabor College", 717],
  ["Tennessee Wesleyan College", 718],
  ["Texas Woman's University", 719],
  ["Union College - Kentucky", 720],
  ["University of Nevada Las Vegas - Nevada", 741],
  ["University of Washington Bothell Campus - Washington", 742],
  ["University of Washington Tacoma Campus", 723],
  ["University of Wisconsin Superior", 724],
  ["Armstrong State University", 725],
  ["Chestnut Hill College", 726],
  ["Eastern Washington University", 727],
  ["Elmira College", 728],
  ["Georgia Southern University", 729],
  ["Meredith College", 730],
  ["Methodist University", 731],
  ["Morehouse College", 732],
  ["Northern Kentucky University", 733],
  ["Northwestern State University of Louisiana", 734],
  ["Trinity College of Florida", 735],
  ["Truett McConnell College", 736],
  ["Wayland Baptist University", 737],
  ["Bluffton University", 738],
  ["Concord University", 739],
  ["Eastern Michigan University", 740],
  ["Johnson & Wales University Denver", 743],
  ["Louisiana State University Shreveport", 744],
  ["Mars Hill College", 745],
  ["Marymount University", 746],
  ["Philadelphia Biblical University Langhorne", 747],
  ["Roger Williams University", 748],
  ["University of Mount Union", 749],
  ["Cazenovia College", 750],
  ["Colby Sawyer College", 751],
  ["Eastern Kentucky University", 752],
  ["Emmanuel College - Georgia", 753],
  ["Husson University", 754],
  ["Kennesaw State University", 755],
  ["Lake Superior State University", 756],
  ["Northwestern Oklahoma State University", 757],
  ["Saint Anselm College", 758],
  ["Spalding University", 759],
  ["SUNY College at Plattsburgh", 760],
  ["Gwynedd Mercy College", 761],
  ["Immaculata University", 762],
  ["Auburn University at Montgomery", 763],
  ["California State University Chico", 764],
  ["Clarion University of Pennsylvania", 765],
  ["Eastern New Mexico University Main Campus", 766],
  ["Fort Lewis College", 767],
  ["Humboldt State University", 768],
  ["Mount Mary College", 769],
  ["Point Park University", 770],
  ["Ringling College of Art and Design", 771],
  ["University of New Orleans", 772],
  ["University of Northern Iowa", 773],
  ["Upper Iowa University", 774],
  ["Alderson Broaddus College", 775],
  ["Austin Peay State University", 776],
  ["Bay Path College", 777],
  ["Bethany College - Kansas", 778],
  ["Bridgewater State University", 779],
  ["California College of the Arts", 780],
  ["University of Maine", 781],
  ["California State University Monterey Bay", 782],
  ["Campbellsville University", 783],
  ["Central Washington University", 784],
  ["College of Mount St. Joseph", 785],
  ["Fairleigh Dickinson University Metropolitan Campus", 786],
  ["Goucher College", 787],
  ["Grand View University", 788],
  ["Hartwick College", 789],
  ["Holy Names University", 790],
  ["Jamestown College", 791],
  ["Lindenwood University", 792],
  ["Menlo College", 793],
  ["Missouri Southern State University", 794],
  ["Monmouth College", 795],
  ["Montclair State University", 796],
  ["Muskingum University", 797],
  ["North Georgia College & State University", 798],
  ["Notre Dame de Namur University", 799],
  ["Roosevelt University", 800],
  ["Rosemont College", 801],
  ["Saint Josephs College", 802],
  ["Salve Regina University", 803],
  ["San Francisco State University", 804],
  ["Shippensburg University of Pennsylvania", 805],
  ["Siena Heights University", 806],
  ["Sonoma State University", 807],
  ["Stevenson University", 808],
  ["SUNY at Purchase College", 809],
  ["SUNY College at Buffalo", 810],
  ["SUNY College at Potsdam", 811],
  ["The Sage Colleges", 812],
  ["University at Buffalo", 813],
  ["University of Louisiana at Lafayette", 814],
  ["University of Saint Francis Fort Wayne", 815],
  ["University of Southern Indiana", 816],
  ["University of Wisconsin Stout", 817],
  ["University of Wisconsin Whitewater", 818],
  ["Watkins College of Art Design & Film", 819],
  ["Western Kentucky University", 820],
  ["Western Oregon University", 821],
  ["Wilmington College", 822],
  ["Cleveland State University", 823],
  ["Henderson State University", 824],
  ["Indiana University Purdue University Fort Wayne", 825],
  ["La Roche College", 826],
  ["Nicholls State University", 827],
  ["Alfred University", 828],
  ["California State University Los Angeles", 829],
  ["California State University Northridge", 830],
  ["California State University San Marcos", 831],
  ["Jacksonville State University", 832],
  ["Kuyper College", 833],
  ["Limestone College", 834],
  ["University of Arkansas at Little Rock", 835],
  ["University of Pittsburgh Bradford", 836],
  ["West Virginia University Institute of Technology", 837],
  ["Worcester State University", 838],
  ["Averett University", 839],
  ["California State University San Bernardino", 840],
  ["Davis & Elkins College - West Virginia", 861],
  ["Georgia Southwestern State University", 842],
  ["Indiana University East", 843],
  ["Kutztown University of Pennsylvania", 844],
  ["Louisiana College", 845],
  ["Warner Pacific College", 846],
  ["Arkansas Tech University", 847],
  ["Augustana College - Illinois", 848],
  ["College for Creative Studies", 849],
  ["Framingham State University", 850],
  ["Guilford College", 851],
  ["Memphis College of Art", 852],
  ["North Park University", 853],
  ["Saint Mary of the Woods College", 854],
  ["University of Minnesota Crookston", 855],
  ["Virginia Intermont College", 856],
  ["Columbus State University", 857],
  ["Culver Stockton College", 858],
  ["Johnson & Wales University Charlotte", 859],
  ["Kentucky Christian University", 860],
  ["Northern Illinois University", 862],
  ["Northwood University Florida", 863],
  ["Oakland City University", 864],
  ["Otis College of Art and Design", 865],
  ["Radford University", 866],
  ["University of Southern Mississippi", 867],
  ["Valdosta State University", 868],
  ["Valley City State University", 869],
  ["Winston Salem State University", 870],
  ["Edinboro University of Pennsylvania", 871],
  ["Lees McRae College", 872],
  ["North Central University", 873],
  ["Northern State University", 874],
  ["Saint Cloud State University", 875],
  ["William Paterson University of New Jersey", 876],
  ["Belmont Abbey College", 877],
  ["Frostburg State University", 878],
  ["Minneapolis College of Art and Design", 879],
  ["Montreat College", 880],
  ["Northern Michigan University - Michigan", 901],
  ["Shimer College", 882],
  ["Southeastern Louisiana University", 883],
  ["Vanguard University of Southern California", 884],
  ["Adams State College", 885],
  ["Cincinnati Christian University", 886],
  ["Columbus College of Art and Design", 887],
  ["Dalton State College", 888],
  ["Johnson & Wales University Providence", 889],
  ["Pennsylvania State University Penn State Abington", 890],
  ["University of North Alabama", 891],
  ["Delta State University", 892],
  ["Marlboro College", 893],
  ["Prescott College", 894],
  ["University of West Georgia", 895],
  ["Western Illinois University", 896],
  ["Woodbury University", 897],
  ["Bemidji State University", 898],
  ["California State University East Bay", 899],
  ["California University of Pennsylvania", 900],
  ["CUNY Hunter College", 902],
  ["Dakota State University", 903],
  ["Eastern Oregon University", 904],
  ["Fairleigh Dickinson University College at Florham", 905],
  ["Fitchburg State University", 906],
  ["Hilbert College", 907],
  ["Keuka College", 908],
  ["Maharishi University of Management", 909],
  ["Marian University - Wisconsin", 910],
  ["Massachusetts College of Liberal Arts", 911],
  ["Milwaukee Institute of Art & Design", 912],
  ["Mount Saint Mary College", 913],
  ["North Carolina Central University", 914],
  ["Rockford College", 915],
  ["Southern Arkansas University Main Campus", 916],
  ["Southern California Institute of Architecture", 917],
  ["SUNY College at Old Westbury", 918],
  ["Tusculum College", 919],
  ["Tuskegee University", 920],
  ["Culinary Institute of America", 921],
  ["Western State College of Colorado", 922],
  ["Wheelock College", 923],
  ["AIB College of Business", 924],
  ["Salem State University", 925],
  ["San Francisco Art Institute", 926],
  ["University of Wisconsin Milwaukee", 927],
  ["Cardinal Stritch University", 928],
  ["Indiana University Southeast", 929],
  ["Kentucky Mountain Bible College", 930],
  ["Pennsylvania State University Penn State Harrisburg", 931],
  ["Purdue University Calumet Campus", 932],
  ["Westfield State University", 933],
  ["Barton College", 934],
  ["Lewis Clark State College", 935],
  ["Thiel College", 936],
  ["William Peace University", 937],
  ["Holy Family University", 938],
  ["Indiana State University", 939],
  ["Indiana University Kokomo", 940],
  ["Indiana University South Bend", 941],
  ["Ohio Valley University", 942],
  ["Saint Peter's College", 943],
  ["Sul Ross State University", 944],
  ["SUNY College at Brockport", 945],
  ["Clark Atlanta University", 946],
  ["Holy Cross College", 947],
  ["Johnson & Wales University North Miami", 948],
  ["Brewton Parker College", 949],
  ["Champlain College", 950],
  ["Norwich University", 951],
  ["Pennsylvania State University Penn State Altoona", 952],
  ["Defiance College", 953],
  ["Oakwood University", 954],
  ["Saint Thomas University", 955],
  ["Becker College", 956],
  ["Concordia University Chicago", 957],
  ["Lesley University", 958],
  ["Pennsylvania State University Penn State Berks", 959],
  ["Prairie View A & M University", 960],
  ["Regis College", 961],
  ["Reinhardt University", 962],
  ["Tiffin University", 963],
  ["Eastern Connecticut State University", 964],
  ["University of Southern Maine", 965],
  ["Vermont Technical College", 966],
  ["Bluefield College", 967],
  ["Cabrini College", 968],
  ["California State University Dominguez Hills", 969],
  ["Clayton State University", 970],
  ["Cleary University", 971],
  ["Colorado Mesa University", 972],
  ["Dillard University", 973],
  ["Eastern Nazarene College", 974],
  ["Erskine College and Seminary", 975],
  ["Iona College", 976],
  ["Kean University", 977],
  ["Lakeland College", 978],
  ["Manhattanville College", 979],
  ["Marygrove College", 980],
  ["Molloy College", 981],
  ["Oregon College of Art and Craft", 982],
  ["Southern New Hampshire University", 983],
  ["The Evergreen State College", 984],
  ["University of Akron Main Campus", 985],
  ["University of Dubuque", 986],
  ["Iowa Wesleyan College", 987],
  ["Macon State College", 988],
  ["Wentworth Institute of Technology", 989],
  ["Central Connecticut State University", 990],
  ["CUNY College of Staten Island", 991],
  ["Fisk University", 992],
  ["Life University", 993],
  ["Pennsylvania State University Penn State Lehigh Valley", 994],
  ["Silver Lake College of the Holy Family", 995],
  ["University of Bridgeport", 996],
  ["University of Maine at Farmington", 997],
  ["University of Wisconsin Parkside", 998],
  ["Brevard College", 999],
  ["Coker College", 1000],
  ["Johnson C Smith University", 1001],
  ["Lyme Academy College of Fine Arts", 1002],
  ["Western Connecticut State University", 1003],
  ["Alcorn State University", 1004],
  ["Metropolitan State College of Denver", 1005],
  ["Texas Southern University", 1006],
  ["Fayetteville State University", 1007],
  ["Goldey Beacom College", 1008],
  ["Paine College", 1009],
  ["Albany State University", 1010],
  ["Delaware State University", 1011],
  ["Utica College", 1012],
  ["Indiana Institute of Technology", 1013],
  ["Jackson State University", 1014],
  ["Purdue University North Central Campus", 1015],
  ["Norfolk State University", 1016],
  ["Mid Atlantic Christian University", 1017],
  ["University of Baltimore", 1018],
  ["Beacon College", 1019],
  ["Bethel University - Tennessee", 1020],
  ["Castleton State College", 1021],
  ["Felician College", 1022],
  ["Grambling State University", 1023],
  ["Long Island University Brooklyn Campus", 1024],
  ["Long Island University C W Post Campus", 1025],
  ["Mercy College", 1026],
  ["Naropa University", 1027],
  ["South Carolina State University", 1028],
  ["University of Maryland Eastern Shore", 1029],
  ["Alabama State University", 1030],
  ["Bethune Cookman University", 1031],
  ["Plymouth State University", 1032],
  ["West Virginia State University", 1033],
  ["Neumann University", 1034],
  ["Southern Connecticut State University", 1035],
  ["Northeastern Illinois University", 1036],
  ["Rivier College", 1037],
  ["Southern Illinois University Carbondale", 1038],
  ["Alverno College", 1039],
  ["Dominican College of Blauvelt", 1040],
  ["Lasell College", 1041],
  ["Indiana University Northwest", 1042],
  ["Anna Maria College", 1043],
  ["Ferrum College", 1044],
  ["Albertus Magnus College", 1045],
  ["Bethany College - West Virginia", 1046],
  ["Huston Tillotson University", 1047],
  ["Lane College", 1048],
  ["Lincoln University of Pennsylvania", 1049],
  ["Southern Vermont College", 1050],
  ["Virginia State University", 1051],
  ["Paul Quinn College", 1052],
  ["Saint Louis Christian College", 1053],
  ["Pennsylvania State University Penn State Schuylkill", 1054],
  ["Mississippi Valley State University", 1055],
  ["Nyack College", 1056],
  ["Savannah State University", 1057],
  ["MacMurray College", 1058],
  ["Robert Morris University Illinois", 1059],
  ["CUNY John Jay College of Criminal Justice", 1060],
  ["Curry College", 1061],
  ["Voorhees College", 1062],
  ["Dowling College", 1063],
  ["Green Mountain College", 1064],
  ["Rust College", 1065],
  ["Wesley College", 1066],
  ["Mitchell College", 1067],
  ["North Carolina A & T State University", 1068],
  ["New England College", 1069],
  ["Morgan State University", 1070],
  ["Newbury College Brookline", 1071],
  ["Chowan University", 1072],
  ["Nichols College", 1073],
  ["Virginia Union University", 1074],
  ["Bloomfield College", 1075],
  ["Central State University", 1076],
  ["Mount Ida College", 1077],
  ["American International College", 1078],
  ["Calumet College of Saint Joseph", 1079],
  ["Le Moyne Owen College", 1080],
  ["Kentucky State University - Kentucky", 1101],
  ["Dean College", 1082],
  ["Saint Augustines College", 1083],
  ["Catawba College", 1084],
  ["Shaw University", 1085],
  ["Fisher College", 1086],
  ["Webber International University", 1087],
  ["Concordia University Ann Arbor", 1088],
  ["Abraham Baldwin Agricultural College", 1089],
  ["Adrian College", 1090],
  ["Alabama A & M University", 1091],
  ["Alaska Pacific University", 1092],
  ["Alice Lloyd College", 1093],
  ["Allen College", 1094],
  ["American Musical and Dramatic Academy", 1095],
  ["American University", 1096],
  ["Amherst College", 1097],
  ["Angelo State University", 1098],
  ["Antioch University Seattle", 1099],
  ["Appalachian Bible College", 1100],
  ["Art Academy of Cincinnati", 1102],
  ["Augsburg College", 1103],
  ["Augusta State University", 1104],
  ["Aurora University", 1105],
  ["Averett University Non Traditional Programs", 1106],
  ["Bacone College", 1107],
  ["Bais Medrash Toras Chesed", 1108],
  ["Baptist Missionary Association Theological Seminary", 1109],
  ["Bates College", 1110],
  ["Baylor University", 1111],
  ["Bellin College", 1112],
  ["Benedictine College", 1113],
  ["Benedictine University", 1114],
  ["Bennett College for Women", 1115],
  ["Bentley University", 1116],
  ["Berklee College of Music", 1117],
  ["Bethesda University of California", 1118],
  ["Black Hills State University", 1119],
  ["Boise Bible College", 1120],
  ["Bon Secours Memorial College of Nursing", 1121],
  ["Boston Baptist College", 1122],
  ["Boston College", 1123],
  ["Bowdoin College", 1124],
  ["Bowie State University", 1125],
  ["Brenau University", 1126],
  ["Brescia University", 1127],
  ["Brigham Young University Hawaii", 1128],
  ["Brown University", 1129],
  ["Bryan University Dayton", 1130],
  ["BryanLGH College of Health Sciences", 1131],
  ["Bryn Athyn College of the New Church", 1132],
  ["Bryn Mawr College", 1133],
  ["Burlington College", 1134],
  ["Cabarrus College of Health Sciences", 1135],
  ["California Christian College", 1136],
  ["California Institute of Technology", 1137],
  ["California Institute of the Arts", 1138],
  ["California Maritime Academy", 1139],
  ["California State University Channel Islands", 1140],
  ["Calvary Bible College and Theological Seminary", 1141],
  ["Campbell University", 1142],
  ["Capitol College", 1143],
  ["Carleton College", 1144],
  ["Carlos Albizu University Miami", 1145],
  ["Carlow University", 1146],
  ["Case Western Reserve University", 1147],
  ["Centenary College", 1148],
  ["Central Baptist College", 1149],
  ["Central Christian College of the Bible", 1150],
  ["Centre College", 1151],
  ["Charles R Drew University of Medicine and Science", 1152],
  ["Charleston Southern University", 1153],
  ["Chicago State University", 1154],
  ["Claremont McKenna College", 1155],
  ["Clarkson College", 1156],
  ["Cleveland Institute of Art", 1157],
  ["Cleveland Institute of Music", 1158],
  ["Colby College", 1159],
  ["College of Coastal Georgia", 1160],
  ["College of Our Lady of the Elms", 1161],
  ["College of Saint Elizabeth", 1162],
  ["College of St Joseph", 1163],
  ["College of the Holy Cross", 1164],
  ["College of the Ozarks", 1165],
  ["Colorado College", 1166],
  ["Colorado State University Pueblo", 1167],
  ["Columbia College Hollywood", 1168],
  ["Columbia University in the City of New York", 1169],
  ["Conception Seminary College", 1170],
  ["Concordia College New York", 1171],
  ["Connecticut College", 1172],
  ["Coppin State University", 1173],
  ["Corcoran College of Art and Design", 1174],
  ["Cornell University", 1175],
  ["Cornish College of the Arts", 1176],
  ["Cottey College", 1177],
  ["Cox College", 1178],
  ["Crossroads College", 1179],
  ["CUNY Bernard M Baruch College", 1180],
  ["CUNY Brooklyn College - New York", 1201],
  ["CUNY City College", 1182],
  ["CUNY Lehman College", 1183],
  ["CUNY Medgar Evers College", 1184],
  ["CUNY New York City College of Technology", 1185],
  ["CUNY York College", 1186],
  ["Dakota Wesleyan University", 1187],
  ["Dallas Christian College", 1188],
  ["Dartmouth College", 1189],
  ["Davenport University", 1190],
  ["Davis College", 1191],
  ["Dell'Arte International School of Physical Theatre", 1192],
  ["DeSales University", 1193],
  ["Dickinson College", 1194],
  ["Dickinson State University", 1195],
  ["Duke University", 1196],
  ["Dunwoody College of Technology", 1197],
  ["D'Youville College", 1198],
  ["East Stroudsburg University of Pennsylvania", 1199],
  ["Ecclesia College", 1200],
  ["Elizabethtown College", 1202],
  ["Embry Riddle Aeronautical University Worldwide", 1203],
  ["Evangel University", 1204],
  ["Fashion Institute of Technology", 1205],
  ["Ferris State University", 1206],
  ["Finlandia University", 1207],
  ["Florida Christian College", 1208],
  ["Florida College", 1209],
  ["Florida Hospital College of Health Sciences", 1210],
  ["Florida Memorial University", 1211],
  ["Fontbonne University", 1212],
  ["Fort Valley State University", 1213],
  ["Franklin and Marshall College", 1214],
  ["Franklin Pierce University", 1215],
  ["Furman University", 1216],
  ["Gainesville State College", 1217],
  ["Gallaudet University", 1218],
  ["Geneva College", 1219],
  ["George Washington University", 1220],
  ["Georgetown University", 1221],
  ["Georgian Court University", 1222],
  ["Glenville State College", 1223],
  ["Gordon College - Georgia", 1224],
  ["Grace Bible College", 1225],
  ["Grace University", 1226],
  ["Greensboro College", 1227],
  ["Grinnell College", 1228],
  ["Hamilton College", 1229],
  ["Hannibal LaGrange University", 1230],
  ["Harvey Mudd College", 1231],
  ["Haverford College", 1232],
  ["Hebrew Theological College", 1233],
  ["Hillsdale Free Will Baptist College", 1234],
  ["Hiram College", 1235],
  ["Hiwassee College", 1236],
  ["Hodges University", 1237],
  ["Hope International University", 1238],
  ["Houston Baptist University", 1239],
  ["Howard University", 1240],
  ["Indiana University of Pennsylvania Main Campus - Pennsylvania", 1241],
  ["Ithaca College", 1242],
  ["James Madison University", 1243],
  ["Jewish Theological Seminary of America", 1244],
  ["Johnson State College", 1245],
  ["Kalamazoo College", 1246],
  ["Kansas Wesleyan University", 1247],
  ["Keene State College", 1248],
  ["Keiser University Ft Lauderdale", 1249],
  ["Kettering College of Medical Arts", 1250],
  ["Keystone College", 1251],
  ["Knox College", 1252],
  ["Laboure College", 1253],
  ["Lake Erie College", 1254],
  ["Lamar University", 1255],
  ["Lancaster Bible College", 1256],
  ["Laurel University", 1257],
  ["Lebanon Valley College", 1258],
  ["Lehigh University", 1259],
  ["Lexington College", 1260],
  ["Indiana University of Pennsylvania Main Campus - California", 1261],
  ["Lincoln College", 1262],
  ["Lincoln University", 1263],
  ["Livingstone College", 1264],
  ["Longy School of Music", 1265],
  ["Louisiana State University Alexandria", 1266],
  ["Lyndon State College", 1267],
  ["Macalester College", 1268],
  ["Maine College of Art", 1269],
  ["Maine Maritime Academy", 1270],
  ["Manhattan School of Music", 1271],
  ["Maranatha Baptist Bible College", 1272],
  ["Maria College of Albany", 1273],
  ["Marquette University", 1274],
  ["Marymount Manhattan College", 1275],
  ["Massachusetts College of Pharmacy and Health Sciences", 1276],
  ["Massachusetts Institute of Technology", 1277],
  ["McPherson College", 1278],
  ["Medaille College", 1279],
  ["Mercy College of Health Sciences", 1280],
  ["Mercy College of Ohio", 1281],
  ["Merrimack College", 1282],
  ["Mesivta Torah Vodaath Rabbinical Seminary", 1283],
  ["Mesivtha Tifereth Jerusalem of America", 1284],
  ["Messenger College", 1285],
  ["Methodist College of Nursing", 1286],
  ["Metropolitan College of New York", 1287],
  ["Michigan Jewish Institute", 1288],
  ["Mid Continent University", 1289],
  ["MidAmerica Nazarene University", 1290],
  ["Middle Georgia College", 1291],
  ["Middlebury College", 1292],
  ["Midland University", 1293],
  ["Midwestern Baptist Theological Seminary", 1294],
  ["Millersville University of Pennsylvania", 1295],
  ["Minnesota State University Mankato", 1296],
  ["Minnesota State University Moorhead", 1297],
  ["Mississippi University for Women", 1298],
  ["Missouri Baptist University", 1299],
  ["Missouri Valley College", 1300],
  ["Montana State University Northern", 1301],
  ["Moody Bible Institute", 1302],
  ["Moore College of Art and Design", 1303],
  ["Morrisville State College", 1304],
  ["Mount Angel Seminary", 1305],
  ["Mount Olive College", 1306],
  ["National Louis University", 1307],
  ["Nazareth College", 1308],
  ["Nebraska Wesleyan University", 1309],
  ["Ner Israel Rabbinical College", 1310],
  ["Nevada State College", 1311],
  ["New England School of Communications", 1312],
  ["New Hope Christian College - Hawaii", 1313],
  ["New Hope Christian College - Oregon", 1314],
  ["New Jersey City University", 1315],
  ["New Jersey Institute of Technology", 1316],
  ["New Mexico State University Main Campus", 1317],
  ["New York College of Health Professions", 1318],
  ["North Carolina Wesleyan College", 1319],
  ["Northeastern University", 1320],
  ["Northland International University - Wisconsin", 1341],
  ["Northwestern Health Sciences University", 1322],
  ["Northwestern University", 1323],
  ["Notre Dame College", 1324],
  ["Oak Hills Christian College", 1325],
  ["Oglethorpe University", 1326],
  ["Ohio Christian University", 1327],
  ["Ohio State University Main Campus", 1328],
  ["Oklahoma Panhandle State University", 1329],
  ["Oklahoma Wesleyan University", 1330],
  ["Olivet College", 1331],
  ["Olivet Nazarene University", 1332],
  ["O'More College of Design", 1333],
  ["Oregon Institute of Technology", 1334],
  ["Ottawa University Ottawa", 1335],
  ["Our Lady of the Lake University San Antonio", 1336],
  ["Pacific Northwest College of Art", 1337],
  ["Palm Beach Atlantic University West Palm Beach", 1338],
  ["Park University", 1339],
  ["Paul Smiths College of Arts and Science", 1340],
  ["Pennsylvania College of Art and Design", 1342],
  ["Pennsylvania College of Health Sciences", 1343],
  ["Pennsylvania State University Penn State Beaver", 1344],
  ["Pennsylvania State University Penn State Brandywine", 1345],
  ["Pennsylvania State University Penn State Dubois", 1346],
  ["Pennsylvania State University Penn State Fayette Eberly Campus", 1347],
  ["Pennsylvania State University Penn State Greater Allegheny", 1348],
  ["Pennsylvania State University Penn State Hazleton", 1349],
  ["Pennsylvania State University Penn State Mont Alto", 1350],
  ["Pennsylvania State University Penn State New Kensington", 1351],
  ["Pennsylvania State University Penn State Shenango", 1352],
  ["Pennsylvania State University Penn State Wilkes Barre", 1353],
  ["Pennsylvania State University Penn State Worthington Scranton", 1354],
  ["Pennsylvania State University Penn State York", 1355],
  ["Piedmont International University", 1356],
  ["Pine Manor College", 1357],
  ["Polytechnic Institute of New York University", 1358],
  ["Pomona College", 1359],
  ["Presentation College", 1360],
  ["Providence Christian College - California", 1381],
  ["Rabbinical College of Ohr Shimon Yisroel - New York", 1382],
  ["Remington College - Florida", 1383],
  ["Remington College Colorado Springs Campus - Colorado", 1384],
  ["Remington College Honolulu Campus - Hawaii", 1385],
  ["Remington College Tampa Campus - Florida", 1386],
  ["Rhode Island College - Rhode Island", 1387],
  ["Rice University - Texas", 1388],
  ["Ripon College - Wisconsin", 1389],
  ["Rochester College - Michigan", 1390],
  ["Rogers State University - Oklahoma", 1391],
  ["Rowan University - New Jersey", 1392],
  ["Rutgers University Camden - New Jersey", 1393],
  ["Rutgers University New Brunswick - New Jersey", 1394],
  ["Rutgers University Newark - New Jersey", 1395],
  ["Saginaw Valley State University - Michigan", 1396],
  ["Saint Edward's University", 1377],
  ["Saint John Vianney College Seminary", 1378],
  ["Saint Joseph's College of Maine", 1379],
  ["Saint Mary's University of Minnesota", 1380],
  ["Southwest Minnesota State University", 1397],
  ["Southwestern Assemblies of God University", 1398],
  ["Southwestern Christian University", 1399],
  ["Southwestern University", 1400],
  ["Saint Thomas Aquinas College", 1401],
  ["St John's College - Maryland", 1402],
  ["St John's College - New Mexico", 1403],
  ["St Mary's College of Maryland", 1404],
  ["St. Francis College", 1405],
  ["State University of New York at New Paltz", 1406],
  ["Stephen F Austin State University", 1407],
  ["Sterling College - Vermont", 1408],
  ["Stevens Institute of Technology", 1409],
  ["Stillman College", 1410],
  ["Suffolk University", 1411],
  ["SUM Bible College and Theological Seminary", 1412],
  ["SUNY College at Cortland", 1413],
  ["SUNY College of Agriculture and Technology at Cobleskill", 1414],
  ["SUNY College of Technology at Alfred", 1415],
  ["SUNY College of Technology at Canton", 1416],
  ["SUNY College of Technology at Delhi", 1417],
  ["SUNY Empire State College", 1418],
  ["SUNY Institute of Technology at Utica Rome", 1419],
  ["SUNY Maritime College", 1420],
  ["Swarthmore College - Pennsylvania", 1441],
  ["Talmudical Yeshiva of Philadelphia - Pennsylvania", 1442],
  ["Tarleton State University - Texas", 1443],
  ["Tennessee Temple University - Tennessee", 1444],
  ["Texas A & M International University - Texas", 1445],
  ["Texas A & M University College Station - Texas", 1446],
  ["Texas A & M University Commerce - Texas", 1447],
  ["Texas A & M University Corpus Christi - Texas", 1448],
  ["Texas A & M University Galveston - Texas", 1449],
  ["Texas A & M University Texarkana - Texas", 1450],
  ["Texas Christian University - Texas", 1451],
  ["Texas State University - Texas", 1452],
  ["Texas Tech University - Texas", 1453],
  ["The Baptist College of Florida - Florida", 1454],
  ["The Boston Conservatory - Massachusetts", 1455],
  ["The College of New Jersey - New Jersey", 1456],
  ["The College of New Rochelle - New York", 1457],
  ["The Juilliard School - New York", 1458],
  ["The King?s College - New York", 1459],
  ["The New England Conservatory of Music", 1440],
  ["Trinity Washington University", 1460],
  ["Trocaire College - New York", 1481],
  ["Troy University", 1462],
  ["Truman State University", 1463],
  ["Tufts University", 1464],
  ["United States Military Academy", 1465],
  ["United States Naval Academy", 1466],
  ["Unity College", 1467],
  ["University of Arkansas at Pine Bluff", 1468],
  ["University of Arkansas Fort Smith", 1469],
  ["University of California San Diego", 1470],
  ["University of California Santa Cruz", 1471],
  ["University of Connecticut", 1472],
  ["University of Connecticut Avery Point", 1473],
  ["University of Connecticut Stamford", 1474],
  ["University of Connecticut Tri Campus", 1475],
  ["University of Detroit Mercy", 1476],
  ["University of Hartford", 1477],
  ["University of Hawaii West Oahu", 1478],
  ["University of Houston", 1479],
  ["University of Houston Victoria", 1480],
  ["University of Maine at Machias", 1482],
  ["University of Mary", 1483],
  ["University of Massachusetts Boston", 1484],
  ["University of Minnesota Rochester", 1485],
  ["University of Minnesota Twin Cities", 1486],
  ["University of Missouri Columbia", 1487],
  ["University of Nebraska Lincoln", 1488],
  ["University of New Hampshire at Manchester", 1489],
  ["University of New Hampshire Main Campus", 1490],
  ["University of North Dakota", 1491],
  ["University of North Texas", 1492],
  ["University of Notre Dame", 1493],
  ["University of Puget Sound", 1494],
  ["University of Richmond", 1495],
  ["University of Sioux Falls", 1496],
  ["University of South Florida St. Petersburg Campus", 1497],
  ["University of Vermont", 1498],
  ["University of West Alabama", 1499],
  ["University of Wisconsin Eau Claire", 1500],
  ["University of Wisconsin La Crosse", 1501],
  ["University of Wisconsin Platteville", 1502],
  ["Ursinus College", 1503],
  ["Valley Forge Christian College", 1504],
  ["Vaughn College of Aeronautics and Technology", 1505],
  ["Villa Maria College", 1506],
  ["Visible Music College", 1507],
  ["Wake Forest University", 1508],
  ["Warner University", 1509],
  ["Washington Adventist University", 1510],
  ["Washington and Lee University", 1511],
  ["Washington University in St Louis", 1512],
  ["Wellesley College", 1513],
  ["Wesleyan College", 1514],
  ["West Texas A & M University", 1515],
  ["Wilberforce University", 1516],
  ["Wilkes University", 1517],
  ["William Carey University", 1518],
  ["William Penn University", 1519],
  ["Williams Baptist College", 1520],
  ["Williams College", 1521],
  ["Wilson College", 1522],
  ["World Mission University", 1523],
  ["Yale University", 1524],
  ["Yeshiva Karlin Stolin", 1525],
  ["Yeshiva Shaar Hatorah", 1526],
  ["Yeshiva Shaarei Torah of Rockland", 1527],
  ["York College", 1528]
]);

// console.log(universityMap.size);

export default universityMap;
